### ISSUE TITLE
Can not create systemd file

### ISSUE THREAD

**Issue by zhuangh7** [elesiuta/picosnitch#11]
![image](https://user-images.githubusercontent.com/16149477/148634673-80dbf48a-f783-44d1-aeed-13c9e08e7fb5.png)

Here is the result.

**Comment by elesiuta** [comment]
Hello, it looks like you're using python 3.7, picosnitch requires python >= 3.8. You should be able to do a dist-upgrade to get python 3.9 but you may run into another issue with your kernel, since it may not be compiled with eBPF support for the raspberry pi. You can check the kernel flags [here](https://github.com/iovisor/bcc/blob/master/INSTALL.md#kernel-configuration).
