### ISSUE TITLE
BPF.support_kfunc() was not True

### ISSUE THREAD

**Issue by lvelvee** [elesiuta/picosnitch#15]
Exception: Failed to load BPF program b'security_socket_connect_entry': Invalid argument
BPF.support_kfunc() was not True, cannot enable bandwidth monitor, check BCC version or Kernel Configuration
picosnitch subprocess died, attempting restart, terminate by running `picosnitch stop`

**Comment by elesiuta** [comment]
This is likely due to the version of BCC on your system being too old. Which distro are you using, and what are your kernel and BCC versions?

**Comment by elesiuta** [comment]
I'm going to close this since it's a dependency issue and not one with picosnitch.

If you're using an Ubuntu based distro, I recommend using [this PPA](https://launchpad.net/~hadret/+archive/ubuntu/bpfcc) since [their repos are pretty far behind](https://repology.org/project/bcc-bpf/versions). You can leave a comment if this wasn't it.
