### ISSUE TITLE
Support for Flatpak/Snap/Appimage

### ISSUE THREAD

**Issue by dtantono** [elesiuta/picosnitch#17]
Hi
to cover wider distributions. Is it possible to get this app in Flatpak/Snap/Appimage?

**Comment by elesiuta** [comment]
Unfortunately Flatpak or AppImage won't work since picosnitch uses the BPF Compiler Collection (BCC) which hasn't been packaged for either, and packaging BPF programs with them might not even be possible due to design.

Snap might be possible since there is a snap for the BPF Compiler Collection (BCC) but I don't have time to look into it much further. If you or someone else is interested in doing it, I can offer pointers, and would gladly merge the snapcraft.yaml file and publish the releases. Also it would likely need [classic confinement](https://snapcraft.io/docs/snap-confinement).

It is probably easier just to package for other distributions, which I can also offer a bit of help with and would gladly merge, which one(s) were you looking for?

**Comment by elesiuta** [comment]
Closing since I don't think this is going to happen, and I just added packages for a number of distros on [copr](https://copr.fedorainfracloud.org/coprs/elesiuta/picosnitch/) and [open build service](https://download.opensuse.org/repositories/home:/elesiuta/), and new issue(s) can be created for any missing distro(s) if there is interest.
