### ISSUE TITLE
Possible to ignore all program/connections where src and dst ip is in 'local' list

### ISSUE THREAD

**Issue by j1warren** [elesiuta/picosnitch#19]
To remove the noise, is that possible currently in configuration?
I see "Log ignore" option, but I guess it will ignore based on src OR dst, which is not applicable for local-to-local connections.

Would be useful to have a list with local IPs, so the connection would be ignored if src AND dst IPs are in this list.

**Comment by elesiuta** [comment]
Correct me if I'm wrong but as far as I know, the source address,  skc_rcv_saddr from struct sock should always be the local address, whether your system is the one to initiate the connection or accept it. So picosnitch only actually logs skc_daddr (or skc_v6_daddr), if you still have a use case that requires skc_rcv_saddr, I may consider adding it or accept a pull request for it.

Otherwise, I just pushed a [commit fixing a regression in log ignore](https://github.com/elesiuta/picosnitch/commit/669e03ae0160d716c257d3eb64101da624d49c76) and another [commit adding support for ignoring IP subnets](https://github.com/elesiuta/picosnitch/commit/6e20d77ac02d8175bc65df21e34589d526ee9b71), so you'll be able to ignore "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16". IP6 should also work.

I haven't tested this yet, but if it looks good and I get a chance, I'll probably do a release sometime next week.

**Comment by elesiuta** [comment]
I just released this with version 0.11.6
