### ISSUE TITLE
picosnitch dash/start-dash not working

### ISSUE THREAD

**Issue by foodornt** [elesiuta/picosnitch#24]
```
$ pacman -Qs picosnitch # arch btw
local/picosnitch 0.11.6-1
    Protect your privacy, see which applications make network connections
```
```
$ picosnitch start-dash
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/picosnitch.py", line 2187, in <module>
    sys.exit(start_picosnitch())
  File "/usr/lib/python3.10/site-packages/picosnitch.py", line 1869, in start_picosnitch
    return ui_dash()
  File "/usr/lib/python3.10/site-packages/picosnitch.py", line 1702, in ui_dash
    app.run(host=os.getenv("HOST", "localhost"), port=os.getenv("PORT", "5100"), debug=bool(eval(os.getenv("DASH_DEBUG", "False"))))
AttributeError: 'Dash' object has no attribute 'run'
```

`picosnitch dash` does open localhost:5100 but there's no server running on that port

**Comment by elesiuta** [comment]
Thanks for the report, `run` has been renamed to `run_server` in the latest version of [dash](https://dash.plotly.com/clientside-callbacks), it looks like this was the only change so it should work as of https://github.com/elesiuta/picosnitch/commit/e35f1f5a35212ebc30bd1b1281d9f8e5b42ca7aa, however I won't have time to test and release this until sometime next week most likely.

**Comment by elesiuta** [comment]
Tested and released version 0.11.7 with the fix for this, picosnitch now works with the latest version of dash in the AUR (2.3.1) and PyPI (2.7.0)

**Comment by SpaceRaccoonFluff** [comment]
I'm having this exact problem, when I in `picosnitch dash` into the terminal I get this:
`Warning: running picosnitch on systems with btrfs is not fully supported due to dev number strangeness and non-unique inodes
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/picosnitch.py", line 2244, in <module>
    sys.exit(start_picosnitch())
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/picosnitch.py", line 1920, in start_picosnitch
    import dash, pandas, plotly
ModuleNotFoundError: No module named 'dash'`

When I visit http://localhost:5100 I get a typical firefox unable to connect error. 

What am I doing wrong?

**Comment by elesiuta** [comment]
You're not doing anything wrong, I suspect this is a bug due to [most distros adopting PEP 668 this month](https://pythonspeed.com/articles/externally-managed-environment-pep-668/) which it looks like you're using since I see python 3.11.

I'll need to update picosnitch to support importing dash from a venv (whether done manually or via pipx as per the link).

**Comment by eeelbrens** [comment]
Well, that issue occurred with me too for both dash and start-dash.
```
$ picosnitch dash
Traceback (most recent call last):
  File "/usr/bin/picosnitch", line 33, in <module>
    sys.exit(load_entry_point('picosnitch==1.0.1', 'console_scripts', 'picosnitch')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/picosnitch.py", line 2323, in start_picosnitch
    import dash, pandas, plotly
ModuleNotFoundError: No module named 'dash'

$ picosnitch start-dash
Traceback (most recent call last):
  File "/usr/bin/picosnitch", line 33, in <module>
    sys.exit(load_entry_point('picosnitch==1.0.1', 'console_scripts', 'picosnitch')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/picosnitch.py", line 2340, in start_picosnitch
    return ui_dash()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/picosnitch.py", line 1730, in ui_dash
    from dash import Dash, dcc, html, callback_context, no_update
ModuleNotFoundError: No module named 'dash'

```

**Comment by elesiuta** [comment]
Which distro are you using? It looks like you may have recently updated it since you're on python 3.12, so you may need to (re)install dash. You can do this by installing `pipx` then running `pipx install dash`.

**Comment by eeelbrens** [comment]
Yup. That worked with me! Thanks!
Ah and I'm using Fedora 39, if that would be of any significance.
