### ISSUE TITLE
Doas instead of sudo.

### ISSUE THREAD

**Issue by Giger22** [elesiuta/picosnitch#37]
Could you add an option to use doas instead of sudo?

**Comment by elesiuta** [comment]
I'd rather not add another option to be configured, so instead would it make sense to use doas as a fallback if sudo is not available, or would it be better to try using doas first if it is available?

The only place that needs updating is here to re-execute itself as root if necessary
https://github.com/elesiuta/picosnitch/blob/a6186afa773b33813294c8e2926ed8f59b9c7f91/picosnitch.py#L2242-L2244

And optionally another elif here if doas provides an environment variable indicating the user that ran it (otherwise it will just fallback to using the first user it finds with a folder in /home)
https://github.com/elesiuta/picosnitch/blob/a6186afa773b33813294c8e2926ed8f59b9c7f91/picosnitch.py#L71-L76

**Comment by Giger22** [comment]
"or would it be better to try using doas first if it is available?"
Personally I would prefer to use doas first.

**Comment by elesiuta** [comment]
I just pushed a commit that should work, I don't use doas and haven't tested it so let me know if this works. Doas does not seem to have an equivalent to the -E flag with sudo, so I'm not sure if this will be an issue.

**Comment by elesiuta** [comment]
Tested and works with the example config [here](https://wiki.archlinux.org/title/Doas#Configuration)
Released with 1.0.3
