### ISSUE TITLE
systemd service recreation still adds Environment var

### ISSUE THREAD

**Issue by glitsj16** [elesiuta/picosnitch#8]
After https://github.com/elesiuta/picosnitch/commit/4b0940282ef028ea1c16d30e597dcc53ac73a6d1 and https://github.com/elesiuta/picosnitch/commit/7526d63159865562325fc390049e95e45fb7629f the systemd service shouldn't need the `Environment` entree anymore. Or to put it differently, `picosnitch systemd` should produce the exact same service unit as https://github.com/elesiuta/picosnitch/blob/master/debian/picosnitch.service.

**Comment by elesiuta** [comment]
Thanks for the contribution, however the Environment entry is still needed if installing from pypi, since the dependencies could also be pulled from there instead of installed as system packages, so it would need to know where the USER_SITE is (and sudo pip install is bad).

Also those commits only offer a slightly better guess than the hard-coded UID of 1000, some people may have multiple home users on their system and this provides an easy way to correct it for those people. Or are using a distribution that may use a different address for DBUS_SESSION_BUS_ADDRESS.
